// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa7A5gTnFwBPopBEEHqcxJ8vlIuQ3_6X8',
    appId: '1:98013227012:web:886bb30711dec4cb5b2d51',
    messagingSenderId: '98013227012',
    projectId: 'newtnet-58210',
    authDomain: 'newtnet-58210.firebaseapp.com',
    storageBucket: 'newtnet-58210.firebasestorage.app',
    measurementId: 'G-1BEPFMKN0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbRC_gGgYNGGlNX8C2nyqOFG3rWI5K9Fc',
    appId: '1:98013227012:android:980b95d304d61a025b2d51',
    messagingSenderId: '98013227012',
    projectId: 'newtnet-58210',
    storageBucket: 'newtnet-58210.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4_aXbEVu1Tdpck2wURV_sOfa3p8d5Hs4',
    appId: '1:98013227012:ios:a2fab9312c9766e85b2d51',
    messagingSenderId: '98013227012',
    projectId: 'newtnet-58210',
    storageBucket: 'newtnet-58210.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationNewtten',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4_aXbEVu1Tdpck2wURV_sOfa3p8d5Hs4',
    appId: '1:98013227012:ios:a2fab9312c9766e85b2d51',
    messagingSenderId: '98013227012',
    projectId: 'newtnet-58210',
    storageBucket: 'newtnet-58210.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationNewtten',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCa7A5gTnFwBPopBEEHqcxJ8vlIuQ3_6X8',
    appId: '1:98013227012:web:18060f72698187435b2d51',
    messagingSenderId: '98013227012',
    projectId: 'newtnet-58210',
    authDomain: 'newtnet-58210.firebaseapp.com',
    storageBucket: 'newtnet-58210.firebasestorage.app',
    measurementId: 'G-3YJ9LVGW71',
  );
}
